### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Chapurin** [kauffecup/react-native-web-hello-world#5]
**logcat:**
 `
12-02 14:28:45.652 10315-10315/? I/art: Not late-enabling -Xcheck:jni (already on)
12-02 14:28:45.652 10315-10315/? W/art: Unexpected CPU variant for X86 using defaults: x86
12-02 14:28:45.764 10315-10315/com.reactnativewebhelloworld D/AndroidRuntime: Shutting down VM

 --------- beginning of crash
12-02 14:28:45.764 10315-10315/com.reactnativewebhelloworld E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.reactnativewebhelloworld, PID: 10315
                                                                          java.lang.RuntimeException: Unable to instantiate application com.reactnativewebhelloworld.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.reactnativewebhelloworld.MainApplication" on path: DexPathList[[zip file "/data/app/com.reactnativewebhelloworld-1/base.apk"],nativeLibraryDirectories=[/data/app/com.reactnativewebhelloworld-1/lib/x86, /system/fake-libs, /data/app/com.reactnativewebhelloworld-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:802)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377)
                                                                              at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.reactnativewebhelloworld.MainApplication" on path: DexPathList[[zip file "/data/app/com.reactnativewebhelloworld-1/base.apk"],nativeLibraryDirectories=[/data/app/com.reactnativewebhelloworld-1/lib/x86, /system/fake-libs, /data/app/com.reactnativewebhelloworld-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:992)
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377) 
                                                                              at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`
`
**manifest.xml**
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.reactnativewebhelloworld">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

**Comment by npomfret** [comment]
Did you solve this?  I've got the same issue.  It happens when I upped the android version from 16 to 22.

**Comment by luizcarlospedrosogomes** [comment]
Did you solve this?
